"""健身管理平台 — 能力注册。"""

SYSTEM = {
    "code": "gym",
    "name": "健身管理平台",
    "description": "会籍办卡、教练课程、健身零售、营销与器材运维。",
    "is_business": True,
    "sort_order": 20,
    "permissions": [
        {"code": "system:gym", "name": "进入健身管理"},
        {"code": "membership:manage", "name": "会籍卡种管理"},
        {"code": "membership:sell", "name": "会籍售卖"},
        {"code": "coach:manage", "name": "教练档案"},
        {"code": "course:manage", "name": "课程排课管理"},
        {"code": "course:book", "name": "团课代约"},
        {"code": "course:checkin", "name": "课程签到核销"},
        {"code": "pt:sell", "name": "私教课包售卖"},
        {"code": "retail:read", "name": "查看零售库存"},
        {"code": "retail:sell", "name": "零售收银"},
        {"code": "retail:manage", "name": "零售商品管理"},
        {"code": "coupon:read", "name": "查看优惠券"},
        {"code": "coupon:manage", "name": "优惠券管理"},
        {"code": "coupon:redeem", "name": "核销优惠券"},
        {"code": "equipment:read", "name": "查看器材"},
        {"code": "equipment:manage", "name": "器材台账管理"},
        {"code": "equipment:repair", "name": "器材报修"},
    ],
    "menus": [
        {
            "code": "gym.products",
            "path": "/products",
            "name": "会籍卡种",
            "required_any": ["membership:manage", "membership:sell", "*"],
            "sort_order": 10,
        },
        {
            "code": "gym.memberships",
            "path": "/memberships",
            "name": "办卡会籍",
            "required_any": ["membership:manage", "membership:sell", "*"],
            "sort_order": 20,
        },
        {
            "code": "gym.coaches",
            "path": "/coaches",
            "name": "教练档案",
            "required_any": ["coach:manage", "*"],
            "sort_order": 30,
        },
        {
            "code": "gym.pt_packages",
            "path": "/pt-packages",
            "name": "私教课包",
            "required_any": ["pt:sell", "course:manage", "*"],
            "sort_order": 40,
        },
        {
            "code": "gym.group_courses",
            "path": "/group-courses",
            "name": "团课排课",
            "required_any": ["course:manage", "course:book", "*"],
            "sort_order": 50,
        },
        {
            "code": "gym.coach_desk",
            "path": "/coach-desk",
            "name": "教练工作台",
            "required_any": ["course:checkin", "course:manage", "*"],
            "sort_order": 60,
        },
        {
            "code": "gym.retail",
            "path": "/retail",
            "name": "零售库存",
            "required_any": ["retail:read", "retail:sell", "retail:manage", "*"],
            "sort_order": 70,
        },
        {
            "code": "gym.coupons",
            "path": "/coupons",
            "name": "优惠券",
            "required_any": ["coupon:read", "coupon:manage", "*"],
            "sort_order": 80,
        },
        {
            "code": "gym.equipment",
            "path": "/equipment",
            "name": "器材台账",
            "required_any": ["equipment:read", "equipment:manage", "equipment:repair", "*"],
            "sort_order": 90,
        },
    ],
}
