"""健身管理平台 — 能力注册。"""

SYSTEM = {
    "code": "gym",
    "name": "观野FIT",
    "description": "会籍办卡、教练课程、健身零售、营销与器材运维。",
    "is_business": True,
    "sort_order": 20,
    "permissions": [
        {"code": "system:gym", "name": "进入观野FIT"},
        {"code": "membership:manage", "name": "会籍卡种管理"},
        {"code": "membership:sell", "name": "会籍售卖"},
        {"code": "coach:manage", "name": "教练档案"},
        {"code": "course:manage", "name": "课程排课管理"},
        {"code": "course:book", "name": "团课代约"},
        {"code": "course:checkin", "name": "课程签到核销"},
        {"code": "pt:sell", "name": "私教课包售卖"},
        {"code": "pt:book", "name": "私教预约排期"},
        {"code": "activity:manage", "name": "活动管理"},
        {"code": "activity:register", "name": "活动报名签到"},
        {"code": "sales:manage", "name": "销售档案管理"},
        {"code": "commission:read", "name": "查看提成"},
        {"code": "commission:manage", "name": "提成规则与结算"},
        {"code": "commission:self", "name": "查看本人佣金与提现"},
        {"code": "retail:read", "name": "查看零售库存"},
        {"code": "retail:sell", "name": "零售收银"},
        {"code": "retail:manage", "name": "零售商品管理"},
        {"code": "coupon:read", "name": "查看优惠券"},
        {"code": "coupon:manage", "name": "优惠券管理"},
        {"code": "coupon:redeem", "name": "核销优惠券"},
        {"code": "equipment:read", "name": "查看器材"},
        {"code": "equipment:manage", "name": "器材台账管理"},
        {"code": "equipment:repair", "name": "器材报修"},
    ],
    "menus": [
        {
            "code": "gym.memberships",
            "path": "/memberships",
            "name": "会籍档案",
            "required_any": ["membership:manage", "membership:sell", "*"],
            "sort_order": 20,
        },
        {
            "code": "gym.products",
            "path": "/products",
            "name": "会籍卡种",
            "required_any": ["membership:manage", "membership:sell", "*"],
            "sort_order": 21,
        },
        {
            "code": "gym.group_courses",
            "path": "/group-courses",
            "name": "团课排课",
            "required_any": ["course:manage", "*"],
            "sort_order": 30,
        },
        {
            "code": "gym.group_bookings",
            "path": "/group-bookings",
            "name": "团课代约",
            "required_any": ["course:book", "course:manage", "*"],
            "sort_order": 31,
        },
        {
            "code": "gym.coach_desk",
            "path": "/coach-desk",
            "name": "团课签到",
            "required_any": ["course:checkin", "course:manage", "*"],
            "sort_order": 32,
        },
        {
            "code": "gym.group_templates",
            "path": "/group-templates",
            "name": "团课模板",
            "required_any": ["course:manage", "*"],
            "sort_order": 33,
        },
        {
            "code": "gym.coaches",
            "path": "/coaches",
            "name": "教练档案",
            "required_any": ["coach:manage", "*"],
            "sort_order": 36,
        },
        {
            "code": "gym.pt_packages",
            "path": "/pt-packages",
            "name": "会员课包",
            "required_any": ["pt:sell", "course:checkin", "course:manage", "*"],
            "sort_order": 40,
        },
        {
            "code": "gym.pt_products",
            "path": "/pt-products",
            "name": "私教课包",
            "required_any": ["pt:sell", "course:manage", "*"],
            "sort_order": 41,
        },
        {
            "code": "gym.pt_appointments",
            "path": "/pt-appointments",
            "name": "私教预约",
            "required_any": ["pt:book", "pt:sell", "course:manage", "course:checkin", "*"],
            "sort_order": 42,
        },
        {
            "code": "gym.activities",
            "path": "/activities",
            "name": "活动管理",
            "required_any": ["activity:manage", "*"],
            "sort_order": 45,
        },
        {
            "code": "gym.activity_registrations",
            "path": "/activity-registrations",
            "name": "活动报名",
            "required_any": ["activity:register", "activity:manage", "*"],
            "sort_order": 46,
        },
        {
            "code": "gym.sales_reps",
            "path": "/sales-reps",
            "name": "销售管理",
            "required_any": ["sales:manage", "commission:manage", "*"],
            "sort_order": 37,
        },
        {
            "code": "gym.commission_rules",
            "path": "/commission-rules",
            "name": "提成规则",
            "required_any": ["commission:manage", "*"],
            "sort_order": 63,
        },
        {
            "code": "gym.commission_settings",
            "path": "/platform/commission-settings",
            "name": "分成配置",
            "required_any": ["commission:manage", "*"],
            "sort_order": 64,
        },
        {
            "code": "gym.commission_records",
            "path": "/commission-records",
            "name": "提成结算",
            "required_any": ["commission:read", "commission:manage", "*"],
            "sort_order": 66,
        },
        {
            "code": "gym.my_commission",
            "path": "/my-commission",
            "name": "我的佣金",
            "required_any": ["commission:self"],
            "sort_order": 67,
        },
        {
            "code": "gym.retail",
            "path": "/retail",
            "name": "库存收银",
            "required_any": ["retail:read", "retail:sell", "retail:manage", "*"],
            "sort_order": 50,
        },
        {
            "code": "gym.retail_categories",
            "path": "/retail-categories",
            "name": "商品分类",
            "required_any": ["retail:read", "retail:manage", "*"],
            "sort_order": 51,
        },
        {
            "code": "gym.retail_catalog",
            "path": "/retail-products",
            "name": "商品管理",
            "required_any": ["retail:read", "retail:manage", "*"],
            "sort_order": 52,
        },
        {
            "code": "gym.equipment",
            "path": "/equipment",
            "name": "器材台账",
            "required_any": ["equipment:read", "equipment:manage", "equipment:repair", "*"],
            "sort_order": 60,
        },
        {
            "code": "gym.equipment_repairs",
            "path": "/equipment-repairs",
            "name": "报修单",
            "required_any": ["equipment:read", "equipment:manage", "equipment:repair", "*"],
            "sort_order": 61,
        },
    ],
}
