"""综合经营管理系统 — 能力注册。"""

SYSTEM = {
    "code": "platform",
    "name": "观野SPACE 综合管理平台",
    "description": "商户组织、员工权限、会员档案、门禁、跨业态订单与报表、子系统与 RBAC 配置。",
    "is_business": False,
    "sort_order": 10,
    "permissions": [
        {"code": "system:platform", "name": "进入观野SPACE"},
        {"code": "org:read", "name": "查看组织"},
        {"code": "org:write", "name": "配置组织"},
        {"code": "staff:manage", "name": "员工与角色管理"},
        {"code": "rbac:manage", "name": "RBAC 配置台"},
        {"code": "member:read", "name": "查看会员"},
        {"code": "member:write", "name": "编辑会员"},
        {"code": "access:read", "name": "查看门禁"},
        {"code": "access:manage", "name": "管理门禁/临访"},
        {"code": "order:read", "name": "查看订单"},
        {"code": "order:write", "name": "创建/收款订单"},
        {"code": "report:read", "name": "经营报表"},
        {"code": "payment:config", "name": "支付通道配置"},
        {"code": "payment:reconcile", "name": "支付对账补单"},
        {"code": "sms:config", "name": "短信配置"},
        {"code": "promoter:read", "name": "查看推广"},
        {"code": "promoter:manage", "name": "推广管理"},
        {"code": "payout:read", "name": "查看提现单"},
        {"code": "payout:manage", "name": "提现审核与打款登记"},
    ],
    "menus": [
        {
            "code": "platform.site_profile",
            "path": "/platform/site-profile",
            "name": "观野SPACE 介绍",
            "required_any": ["org:write", "org:read", "*"],
            "sort_order": 99,
        },
        {
            "code": "platform.subsystems",
            "path": "/platform/subsystems",
            "name": "子系统配置",
            "required_any": ["rbac:manage", "*"],
            "sort_order": 100,
        },
        {
            "code": "platform.roles",
            "path": "/platform/roles",
            "name": "角色配置",
            "required_any": ["rbac:manage", "staff:manage", "*"],
            "sort_order": 90,
        },
        {
            "code": "platform.payment",
            "path": "/platform/payment-settings",
            "name": "京东支付",
            "required_any": ["payment:config", "*"],
            "sort_order": 101,
        },
        {
            "code": "platform.sms",
            "path": "/platform/sms-settings",
            "name": "短信配置",
            "required_any": ["sms:config", "*"],
            "sort_order": 102,
        },
        {
            "code": "platform.agreements",
            "path": "/platform/agreements",
            "name": "协议管理",
            "required_any": ["org:read", "org:write", "*"],
            "sort_order": 103,
        },
        {
            "code": "platform.payment_reconcile",
            "path": "/platform/payment-reconcile",
            "name": "支付对账",
            "required_any": ["payment:reconcile", "*"],
            "sort_order": 21,
        },
        {
            "code": "platform.merchants",
            "path": "/merchants",
            "name": "商户组织",
            "required_any": ["org:read", "*"],
            "sort_order": 80,
        },
        {
            "code": "platform.merchant_types",
            "path": "/merchant-types",
            "name": "商户类型",
            "required_any": ["org:read", "*"],
            "sort_order": 81,
        },
        {
            "code": "platform.staff",
            "path": "/staff",
            "name": "员工与权限",
            "required_any": ["staff:manage", "*"],
            "sort_order": 91,
        },
        {
            "code": "platform.members",
            "path": "/members",
            "name": "会员档案",
            "required_any": ["member:read", "*"],
            "sort_order": 30,
        },
        {
            "code": "platform.access",
            "path": "/access",
            "name": "门禁设备",
            "required_any": ["access:read", "*"],
            "sort_order": 70,
        },
        {
            "code": "platform.visits",
            "path": "/visits",
            "name": "临访登记",
            "required_any": ["access:manage", "access:read", "*"],
            "sort_order": 40,
        },
        {
            "code": "platform.orders",
            "path": "/orders",
            "name": "订单收款",
            "required_any": ["order:read", "*"],
            "sort_order": 20,
        },
        {
            "code": "platform.ops",
            "path": "/ops",
            "name": "经营工作台",
            "required_any": ["system:gym", "system:catering", "report:read", "*"],
            "sort_order": 10,
        },
        {
            "code": "platform.reports",
            "path": "/reports",
            "name": "经营报表",
            "required_any": ["report:read", "*"],
            "sort_order": 11,
        },
        {
            "code": "platform.coupon-templates",
            "path": "/coupons/templates",
            "name": "券模板管理",
            "required_any": ["coupon:read", "coupon:manage", "*"],
            "sort_order": 50,
        },
        {
            "code": "platform.coupon-issue",
            "path": "/coupons/issue",
            "name": "发放优惠券",
            "required_any": ["coupon:read", "coupon:manage", "*"],
            "sort_order": 51,
        },
        {
            "code": "platform.promotion_config",
            "path": "/platform/promotion-config",
            "name": "推广配置",
            "required_any": ["promoter:read", "promoter:manage", "*"],
            "sort_order": 52,
        },
        {
            "code": "platform.promotion_settings",
            "path": "/platform/promotion-settings",
            "name": "推广方案",
            "required_any": ["promoter:read", "promoter:manage", "*"],
            "sort_order": 53,
        },
        {
            "code": "platform.rebates",
            "path": "/rebates",
            "name": "会员返点",
            "required_any": ["promoter:read", "promoter:manage", "*"],
            "sort_order": 54,
        },
        {
            "code": "platform.payouts",
            "path": "/payouts",
            "name": "提现审核",
            "required_any": ["payout:read", "payout:manage", "*"],
            "sort_order": 55,
        },
        {
            "code": "platform.notifications",
            "path": "/notifications",
            "name": "站内通知",
            "required_any": ["order:read", "member:read", "access:read", "*"],
            "sort_order": 60,
        },
    ],
}
