"""综合经营管理系统 — 能力注册。"""

SYSTEM = {
    "code": "platform",
    "name": "综合经营管理系统",
    "description": "商户组织、员工权限、会员主档、门禁、跨业态订单与报表、子系统与 RBAC 配置。",
    "is_business": False,
    "sort_order": 10,
    "permissions": [
        {"code": "system:platform", "name": "进入综合经营"},
        {"code": "org:read", "name": "查看组织"},
        {"code": "org:write", "name": "配置组织"},
        {"code": "staff:manage", "name": "员工与角色管理"},
        {"code": "rbac:manage", "name": "RBAC 配置台"},
        {"code": "member:read", "name": "查看会员"},
        {"code": "member:write", "name": "编辑会员"},
        {"code": "access:read", "name": "查看门禁"},
        {"code": "access:manage", "name": "管理门禁/临访"},
        {"code": "order:read", "name": "查看订单"},
        {"code": "order:write", "name": "创建/收款订单"},
        {"code": "report:read", "name": "经营报表"},
    ],
    "menus": [
        {
            "code": "platform.subsystems",
            "path": "/platform/subsystems",
            "name": "子系统配置",
            "required_any": ["rbac:manage", "*"],
            "sort_order": 5,
        },
        {
            "code": "platform.roles",
            "path": "/platform/roles",
            "name": "角色权限",
            "required_any": ["rbac:manage", "staff:manage", "*"],
            "sort_order": 6,
        },
        {
            "code": "platform.merchants",
            "path": "/merchants",
            "name": "商户组织",
            "required_any": ["org:read", "*"],
            "sort_order": 10,
        },
        {
            "code": "platform.staff",
            "path": "/staff",
            "name": "员工与权限",
            "required_any": ["staff:manage", "*"],
            "sort_order": 20,
        },
        {
            "code": "platform.members",
            "path": "/members",
            "name": "会员主档",
            "required_any": ["member:read", "*"],
            "sort_order": 30,
        },
        {
            "code": "platform.access",
            "path": "/access",
            "name": "门禁设备",
            "required_any": ["access:read", "*"],
            "sort_order": 40,
        },
        {
            "code": "platform.visits",
            "path": "/visits",
            "name": "临访登记",
            "required_any": ["access:manage", "access:read", "*"],
            "sort_order": 50,
        },
        {
            "code": "platform.orders",
            "path": "/orders",
            "name": "订单收款",
            "required_any": ["order:read", "*"],
            "sort_order": 60,
        },
        {
            "code": "platform.reports",
            "path": "/reports",
            "name": "经营报表",
            "required_any": ["report:read", "*"],
            "sort_order": 70,
        },
        {
            "code": "platform.notifications",
            "path": "/notifications",
            "name": "站内通知",
            "required_any": ["order:read", "member:read", "access:read", "*"],
            "sort_order": 80,
        },
    ],
}
